routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Hello\HelloFacade as Hello;
use App\Http\Controllers\TestController;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('/home', function () {
    return view('test');
})->middleware('auth'); //need to login to access this route


// //Route::redirect('foo', 'baz'); //used to redirect to a specific route

// Route::get('foo', function () {
//     return Auth::user();
// })->name('anurag');


Route::view('/testview', 'testview');   //just returns a view

// Route::get('test/{data}', 'TestController@testPrint'); //calls a method in controller along with parameter

// Route::get('user/{id}', function($id){ //  route parameters used to capture segements form the uri  
//     return 'user'. $id;
// });

// Route::get('user/{id}/content/{name}', function($id, $name){ //can capture more than one parameter
//     return "id: " . $id . " name: " . $name;
//     //return redirect()->route('anurag');//this will redirect to route named 'anurag'

// });

// Route::get('movie/{id}/actor/{name?}', function($id, $name = null){ // parameters can also be defualt and optional
//     return "id: " . $id . " name: " . $name;
// })->where('id', '[0-9]+'); //constrain the format of your route parameters using regular expressions

// Route::get('');
Auth::routes(['register' => true]); //disables register new users

Route::post('accounts/getAccounts/','AccountController@getAccounts')->name('accounts.getAccounts');
Route::get('accounts/getRelatedContacts/{accountId}','AccountController@getRelatedContacts')->name('accounts.getRelatedContacts');
Route::post('accounts/massUpdateAccounts/','AccountController@massUpdateAccounts')->name('accounts.massUpdateAccounts');
Route::post('accounts/massDeleteAccounts/','AccountController@massDeleteAccounts')->name('accounts.massDeleteAccounts');

//written above the resource routes


Route::resource('accounts', 'AccountController')->middleware('auth');  
Route::resource('contacts', 'ContactController')->middleware('auth');
//role using spatie   
// Route::resource('users', 'UserController')->middleware(['auth', 'can:create-users', 'can:delete-users', 'can:edit-users']);  

Route::resource('users', 'UserController')->middleware('auth');  

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/test', function() {
    //Hello::helloInHindi(); using facade
    //App::make('hello')->helloInHindi(); //without using facade
    app('hello')->helloInHindi(); // without facade and using app() helper
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'user_role', 'allowed_modules', 'allowed_operations', 'password'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    //used without package for roles
    // public function isAdmin()
    // {
    //     return $this->user_role === 'admin';
    // }

    // public function isUser()
    // {
    //     return $this->user_role === 'user';
    // }

    public function isModuleAllowed($moduleName)
    {
        $modulesAllowed = explode(',', $this->allowed_modules);
        return in_array($moduleName, $modulesAllowed);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Interfaces\UserRepositoryInterface;
use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function __construct(UserRepositoryInterface $user)
    {
        $this->userRepo = $user;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //dd(in_array('contacts', ['accounts', 'users', 'contacts', 'activities']));
        //dump(User::all()->toArray());
        $users = User::all();
        // dd($user);
        $this->authorize('view', User::class);
        return view('users.index' , compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', User::class);
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd($request->all());
        $this->authorize('create', User::class);
        $this->userRepo->create($request);
        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('links')
@endsection

@section('content')
{!! Form::open(['route' => 'users.store', 'method' => 'POST', 'class' => 'form-horizontal']) !!}
@csrf
@include('users.form')
{!! Form::close() !!}
@endsection

@section('scripts')
<script>
    $('.user_role_select').on('change', function() {
        if(this.value == 'admin')
        {
            $('input[value="account"]').prop('checked', true);
            $('input[value="contact"]').prop('checked', true);
            $('input[value="user"]').prop('checked', true);
        }

        if(this.value == 'user')
        {
            $('input[value="account"]').prop('checked', true);
            $('input[value="contact"]').prop('checked', true);
            $('input[value="user"]').prop('checked', false);
        }
    });
</script>
@endsection

resources/views/users/form.blade.php
{!! Form::submit('Save', ['class' => 'btn btn-save']) !!}
<a href="{{ route('users.index') }}" class="btn btn-warning btn-cancel">Cancel</a>
<div class="form">

    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
        {!! Form::label('name', 'User Name') !!}
        {!! Form::text('name', null, ['class' => 'form-control', 'required' => 'required']) !!}
        <small class="text-danger">{{ $errors->first('name') }}</small>
    </div>

   <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
   {!! Form::label('email', 'Email') !!} <br>
   {!! Form::email('email', null, ['class' => 'form-control', 'required' => 'required']) !!}
   <small class="text-danger">{{ $errors->first('email') }}</small>
   </div>

   <div class="form-group{{ $errors->has('user_role') ? ' has-error' : '' }}">
    {!! Form::label('user_role', 'Role') !!} <br>
    {!! Form::select('user_role', ['' => '', 'admin' => 'Admin', 'user' => 'User'], ['id' => 'account_name', 'required' => 'required'], ['class' => 'form-control select user_role_select']) !!}
    <small class="text-danger">{{ $errors->first('user_role') }}</small>
    </div>

    <div class="form-group">
    <div class="checkbox{{ $errors->has('allowed_modules') ? ' has-error' : '' }}">
    <label for="allowed_modules">Allowed Modules:</label><br>
    <label for="account">
    {!! Form::checkbox('allowed_modules[]', 'account', null, ['id' => 'allowed_modules']) !!} Account
    </label><br>

    <label for="contact">
        {!! Form::checkbox('allowed_modules[]', 'contact', null, ['id' => 'allowed_modules']) !!} Contact
    </label><br>

    <label for="user">
        {!! Form::checkbox('allowed_modules[]', 'user', null, ['id' => 'allowed_modules']) !!} User
    </label><br>
        
    </div>
    <small class="text-danger">{{ $errors->first('checkbox_id') }}</small>
    </div>

   <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
        {!! Form::label('password', 'Password') !!} <br>
        {!! Form::password('password', ['class' => 'form-control', 'id' => 'password']) !!}
        <small class="text-danger">{{ $errors->first('password') }}</small>
    </div>

    <div class="form-group{{ $errors->has('confirm_password') ? ' has-error' : '' }}">
        {!! Form::label('confirm_password', 'Confirm Password') !!}
        {!! Form::password('confirm_password', ['class' => 'form-control']) !!}
        <small class="text-danger">{{ $errors->first('confirm_password') }}</small>
    </div>

    

resources/views/users/index.blade.php
@extends('layouts.app')

@section('links')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">
@endsection
@section('content')
    <div class="container">
        <table class="table table-bordered data-table" width="100%">
            <thead>
                <tr>
                    <th>id</th>
                    <th>User Name</th>
                    <th>Email</th>
                 </tr>
            </thead>
            <tbody>
                @foreach ($users as $user)
                    <tr>
                        <td> {{ $user->id }} </td>
                        <td> {{ $user->name }} </td>
                        <td> {{ $user->email }} </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endsection
@section('scripts')
    <script src="{{ asset('js/min.js') }}"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script>
        //  var table = $('.data-table').DataTable({
        //         processing: true,
        //         serverSide: false,
        //         // ajax: {
        //         //     url: "{{ route('accounts.index') }}",
        //         //     //dataSrc: 'data'
        //         // },
        //         ajax:  "{{ route('contacts.index') }}",
        //         columns: [
        //             {data: 'name', name: 'name'},
        //             {data: 'account_name', name: 'account_name'},
        //             {data: 'email', name: 'email'},
        //             {data: 'phone', name: 'phone'},
        //             {data: 'designation', name: 'designation'},
        //             {data: 'department', name: 'department'},
        //             {data: 'hierarchy', name: 'hierarchy'},
        //             {data: 'customer_type', name: 'customer_type'},
        //             {data: 'assigned_to', name: 'assigned_to'},
        //             {data: 'created_at', name: 'created_at'},
        //             {data: 'updated_at', name: 'updated_at'},
        //         ],
        //     scrollX: true,
        //     });
    </script>
@endsection